name: Build Spring Boot JAR, Dockerize, and Push to Docker Hub

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Build Spring Boot JAR
      run: |
        chmod +x backend/real_estate_rental_system/mvnw  # Ensure the wrapper is executable
        ./backend/real_estate_rental_system/mvnw clean package -DskipTests

    - name: Verify JAR exists
      run: ls -lh  ./backend/real_estate_rental_system/target/*.jar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Git Commit SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Tag Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ env.sha_short }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ env.sha_short }}

    - name: Print Image URL
      run: echo "Docker image pushed: ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest"
