name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Spring Boot JAR
      run: |
        chmod +x mvn
        ./mvn clean package -DskipTests

    - name: Deploy to AWS EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
      run: |
        echo "$EC2_PEM_KEY" > key.pem
        chmod 600 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem target/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.jar
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          pkill -f app.jar || true
          nohup java -jar /home/$EC2_USER/app.jar > app.log 2>&1 &
        EOF
